version: '3.8'

services:
  # --- Databases ---
  postgres:
    image: postgres:15-alpine
    container_name: dx-seed-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dx-seed-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d dx-seed-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6.0
    container_name: dx-seed-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # --- Backend Services (Node.js) ---
  auth-service:
    build: ./auth-service
    container_name: dx-seed-auth-service
    ports: [ "3001:3001" ]
    environment: [ "DATABASE_URL=postgresql://user:password@postgres:5432/dx-seed-db" ]
    depends_on: { postgres: { condition: service_healthy } }

  lms-service:
    build: ./lms-service
    container_name: dx-seed-lms-service
    ports: [ "3003:3003" ]
    environment: [ "DATABASE_URL=postgresql://user:password@postgres:5432/dx-seed-db" ]
    depends_on: { postgres: { condition: service_healthy } }

  employment-service:
    build: ./employment-service
    container_name: dx-seed-employment-service
    ports: [ "3007:3007" ]
    environment: [ "DATABASE_URL=postgresql://user:password@postgres:5432/dx-seed-db" ]
    depends_on: { postgres: { condition: service_healthy } }

  project-service:
    build: ./project-service # 不足していたサービス
    container_name: dx-seed-project-service
    ports: [ "3005:3005" ]
    environment: [ "DATABASE_URL=postgresql://user:password@postgres:5432/dx-seed-db" ]
    depends_on: { postgres: { condition: service_healthy } }

  payment-service:
    build: ./payment-service # 不足していたサービス
    container_name: dx-seed-payment-service
    ports: [ "3006:3006" ]
    environment: [ "DATABASE_URL=postgresql://user:password@postgres:5432/dx-seed-db" ]
    depends_on: { postgres: { condition: service_healthy } }
  
  translation-service:
    build: ./translation-service # 不足していたサービス
    container_name: dx-seed-translation-service
    ports: [ "3010:3010" ]

  # --- Backend Services (Python/FastAPI) ---
  matching-service:
    build: ./matching-service
    container_name: dx-seed-matching-service
    ports: [ "3004:8000" ]
    environment: [ "DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/dx-seed-db" ]
    depends_on: { postgres: { condition: service_healthy } }

  support-service:
    build: ./support-service # 不足していたサービス
    container_name: dx-seed-support-service
    ports: [ "3008:8000" ]
    depends_on: { postgres: { condition: service_healthy } }

  analytics-service:
    build: ./analytics-service # 不足していたサービス
    container_name: dx-seed-analytics-service
    ports: [ "3009:8000" ]
    environment:
      - POSTGRES_URL=postgresql://user:password@postgres:5432/dx-seed-db
      - MONGO_URL=mongodb://mongo:27017
    depends_on: [ postgres, mongo ]

  # --- Frontend Service ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dx-seed-frontend
    ports:
      - "5173:80" # Nginxのデフォルトポート80にマッピング

volumes:
  postgres_data:
  mongo_data: